### ISSUE TITLE
AuthController login action not setting expiresInMinutes option

### ISSUE THREAD

**Issue by DigitalIdeaFactory** [ryanwebber/sails-authorization#1]
I implemented your code and found that my tokens were not expiring. It turns out that Passport is passing an array to the callback argument labeled 'user.' That single item array instead of the user object was causing  jwt to fail to add the option { expiresInMinutes: 60*24 }. To fix this it should pass the user object to the jwt.sign method instead of the array.
Thanks for the code though. It got me 95% of the way there!

**Comment by ryanwebber** [comment]
Glad I could help. Thanks for the feedback!
